branches: 
  only:
    - development
    - master
env: 
  matrix: 
    - "CONFIG=release QT_VERSION_FULL=5.12.2"
language: cpp
matrix: 
  include: 
    - 
      compiler: gcc
      dist: bionic
      os: linux
      sudo: required
    - 
      compiler: clang
      os: osx
before_install: 
  - "if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y ppa:beineri/opt-qt-$QT_VERSION_FULL-bionic; sudo apt-get update; sudo apt-get install --force-yes -qq libglu1-mesa-dev freeglut3-dev mesa-common-dev qt512base qt512tools; fi"
  - "if [ $TRAVIS_OS_NAME == osx ]; then brew update; brew cleanup; brew install qt5; brew link --force qt5; sudo ln -s /usr/local/Cellar/qt5/$QT_VERSION_FULL/mkspecs /usr/local/mkspecs; echo 'export PATH=\"/usr/local/opt/qt/bin:$PATH\"' >> ~/.bash_profile; fi"
script: 
  - "if [ $TRAVIS_OS_NAME == linux ]; then cd src/; source /opt/qt512/bin/qt512-env.sh; qmake \"CONFIG+=release silent\"; make -j$(nproc); fi"
  - "if [ $TRAVIS_OS_NAME == osx ]; then cd src/; PATH=/usr/local/Cellar/qt5/$QT_VERSION_FULL/bin:$PATH; qmake \"CONFIG+=release silent\"; make -j$(nproc); fi"
