version: 0.0.{build}-{branch}

image: Visual Studio 2015
platform: x64

branches:
  only:
    - development
    - master
    - features/flat-buffers-CI-configuration
  
environment:
  QT_INSTALL_ROOT: C:\Qt\5.12.4\msvc2015_64
  FLATBUFFERS_PATH: C:\flatbuffers
  FLATC_ZIP_NAME: flatc_windows_exe.zip
  FLATBUFFERS_INCLUDE_DIR: C:\Program Files\FlatBuffers\include
  FLATBUFFERS_LIB_DIR: C:\Program Files\FlatBuffers\lib
  PATH: C:\Program Files\FlatBuffers\bin;%PATH%

install:
  - cmd: >-
      cd C:\
      
      git clone https://github.com/google/flatbuffers.git
      
      cd %FLATBUFFERS_PATH%
      
      git checkout 9e7e8cb
      
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
      
      cmake . -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DFLATBUFFERS_CODE_SANITIZE=1
      
      nmake
      
      nmake install
      
      cd %APPVEYOR_BUILD_FOLDER%\src

pull_requests:
  do_not_increment_build_number: true

build_script:
- cmd: >-
    
    %QT_INSTALL_ROOT%\bin\qtenv2.bat

    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
    
    cd %APPVEYOR_BUILD_FOLDER%\src
    
    qmake CONFIG+=release
    
    nmake

    cd %APPVEYOR_BUILD_FOLDER%\src\tests\projectviewerwindow
    
    qmake tests.pro DESTDIR=.

    nmake

    cd %APPVEYOR_BUILD_FOLDER%\src\tests\projectviewerwindow\release

    tests.exe
     
